### PR TITLE
Enhanced header,footer & start button

### PR DESCRIPTION
**Pull request by kanchanraiii**
i have centered the start button with hover effect, added proper header and footers, and centered the game container and button.

### CODE REVIEW

**Comment by kanchanraiii** [comment]
@bhanusingh008 kindly check the pr

**Comment by bhanu-io** [comment]
https://github.com/user-attachments/assets/68299f76-f5ef-462c-9231-8fc5c893d92a

On mobile screen there is positioning issue, can you have a look at it? @kanchanraiii

**Comment by kanchanraiii** [comment]
ok will fix it. @bhanusingh008

**Comment by kanchanraiii** [comment]
fixed the issue please check @bhanusingh008

**Comment by bhanu-io** [comment]
okay it looks great, thanks @kanchanraiii

**Comment by kanchanraiii** [comment]
please merge it under hacktoberfest. @bhanusingh008 
thanks!

**Pull request merged**
